### ISSUE TITLE
"Key Given" - for arrivals only

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-housekeeping#10]
Can you please add the icon: https://banner2.kisspng.com/20180410/tce/kisspng-computer-icons-key-exchange-lease-5accc6d8808916.2689477515233696885265.jpg to act as a button to say that the key was given?

I think the picture explains it all.
When the button is pressed - the picture can change to https://thumbs.dreamstime.com/b/house-key-hand-icon-real-estate-agent-holds-home-concept-selling-renting-template-vector-illustration-flat-92169196.jpg to show that the key is indeed given.

It should be only for arrivals, per person.
I think - for logging purposes - the last click or unclick for an arrival for a day should be persisted for later analysis.

It will also be important to be able to filter through this checkbox. For example - "who is supposed to arrive today and hasn't received a key yet?"

**Comment by danthareja** [comment]
@iswara108, I'll have to work on the logos, but the functionality is there.

**Comment by danthareja** [comment]
I found an edge case - two guests with the same name in a room. I'll have to key off reservationId instead of guest name

**Comment by danthareja** [comment]
Edge case has been fixed. Logos still need work though.

**Comment by danthareja** [comment]
The functionality has been added, so I'm closing this issue.

See #7 for filtering
See #15 for icons
