### ISSUE TITLE
Add an assigned "Housekeeper" name

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-housekeeping#11]
Can you please have an option to choose a housekeeper for each room?
One way to do it - is free text.
Another way to do it - is a list that gets set up somewhere.

The ideal way I can think of - is a free text for the name of the housekeeper, and once one housekeeper has been assigned, the name appears as the user starts typing it in.

Ideally - only the "housekeeping manager" role should be able to assign housekeepers

**Comment by danthareja** [comment]
@iswara108, is it possible to create unique accounts for each housekeeper?

with this, we can assign them the housekeeper role, limiting their access and/or showing a more optimal view for them on the field and have a prepopulated drop down/autocomplete for the housekeeping manager

This will also allow us to track each housekeeper as they clean rooms

**Comment by danthareja** [comment]
@iswara108, is it possible to create unique accounts for each housekeeper?

with this, we can assign them the housekeeper role, limiting their access and/or showing a more optimal view for them on the field and have a prepopulated drop down/autocomplete for the housekeeping manager

This will also allow us to track each housekeeper as they clean rooms

**Comment by iswara108** [comment]
Yes, that would be great. They will resist, but we'll gently force them to
use their personal emails.
Worst case scenario - we'll create numerous sivananda.org accounts for
housekeeping.

**Comment by iswara108** [comment]
This became irrelevant now.
