### ISSUE TITLE
"Being Cleaned now"

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-housekeeping#2]
Can you add an option for the housekeeper to say "I'm cleaning this room now"? So we can know exactly which rooms are being cleaned in real time.

It should only allow one room per housekeeper at a time.

**Comment by danthareja** [comment]
@iswara108, this one (as with #11) will depend on housekeepers having unique accounts.

**Comment by iswara108** [comment]
OK, let's do it with unique accounts, then.

**Comment by iswara108** [comment]
housekeeping rejected this.
