### ISSUE TITLE
Room Set up Notes

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-housekeeping#3]
I've just added an admin only question: "room-set-up-notes".
It should be populated soon in the API.

Can you please display it for arrivals?

Normal cases of this would be:
"Two single beds"
"One king bed"
"Need an extra cot bed and one crib"

**Comment by iswara108** [comment]
Right, this is pending still.

**Comment by iswara108** [comment]
The API has now a new addition to the request: include=all_questions.

It's in the documentation of their API now.

This should help solve the late check-out and the room set up notes.

**Comment by danthareja** [comment]
Thanks for the update @iswara108. I'll add these shorty.

**Comment by iswara108** [comment]
This is second priority, we have the "Room Set up" question and also "Late checkout" question.

**Comment by danthareja** [comment]
Shipped!
